version: "2"

services:
  db:
    image: postgres:11
    environment:
      POSTGRES_PASSWORD: medpost10
      POSTGRES_USER: postgres
  web:
    build:
      context: .
      args:
        - DJANGO_ENV=production
    command: bash -c "python manage.py makemigrations location --settings=medcombo.settings.production
                      && python manage.py makemigrations company --settings=medcombo.settings.production
                      && python manage.py makemigrations usercustom --settings=medcombo.settings.production
                      && python manage.py makemigrations product --settings=medcombo.settings.production
                      && python manage.py makemigrations contacts --settings=medcombo.settings.production
                      && python manage.py makemigrations catalogue --settings=medcombo.settings.production
                      && python manage.py makemigrations call --settings=medcombo.settings.production
                      && python manage.py makemigrations contact --settings=medcombo.settings.production
                      && python manage.py makemigrations dashboard_admin --settings=medcombo.settings.production
                      && python manage.py makemigrations opportunity --settings=medcombo.settings.production
                      && python manage.py makemigrations task --settings=medcombo.settings.production
                      && python manage.py makemigrations post --settings=medcombo.settings.production
                      && python manage.py makemigrations job --settings=medcombo.settings.production
                      && python manage.py makemigrations economic --settings=medcombo.settings.production
                      && python manage.py migrate --settings=medcombo.settings.production
                      && gunicorn medcombo.wsgi_production:application --bind 0.0.0.0:8000"

    volumes:
      - ./medcombo:/medcombo
    ports:
      - "8000:8000"
    depends_on:
      - db

  nginx:
    restart: always
    build: ./nginx_production  
    ports:
      - "80:80"
    volumes:
      - ./medcombo/static:/var/www/static
    links:
      - web:web