"""
Django settings for medcombo project.

Generated by 'django-admin startproject' using Django 2.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os
import smtplib
#from django.utils.translation import gettext_lazy as _

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '(yzb03rk+yyw*=)tmui4m_r-u!3zi7fno7p-1+a-jbgj7@wza@'

# SECURITY WARNING: don't run with debug turned on in production!



# Application definition

INSTALLED_APPS = [
    'cities_light',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sitemaps',
    'captcha',
    'import_export',
    'dal',
    'dal_select2',
    'pure_pagination',
    #'storages',
    'corsheaders',
    'medcombo.configuration.location',
    'medcombo.configuration.company',            
    'medcombo.configuration.usercustom',
    'medcombo.product',
    'medcombo.social_network.contacts',
    'medcombo.crm',
    'medcombo.myweb.catalogue',
    'medcombo.crm.admins',
    'medcombo.crm.call',
    'medcombo.crm.economic',
    'medcombo.crm.contact',
    'medcombo.crm.dashboard_admin',    
    'medcombo.crm.lead',
    'medcombo.crm.opportunity',
    'medcombo.crm.products',
    'medcombo.crm.task',
    'medcombo.myweb.dashboard_client.post',
    'medcombo.myweb.job',
    'medcombo.website.home',
]


THIRD_PARTY_APPS = (

)

INSTALLED_APPS += THIRD_PARTY_APPS

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.gzip.GZipMiddleware',
    'htmlmin.middleware.HtmlMinifyMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ORIGIN_ALLOW_ALL = True

ROOT_URLCONF = 'medcombo.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'medcombo.configuration.usercustom.context_processors.datauser',
                'medcombo.crm.dashboard_admin.context_processors.get_company_logos',
                'django.template.context_processors.i18n',
            ],
        },
    },
]

WSGI_APPLICATION = 'medcombo.wsgi.application'

# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases



# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'en'

_ = lambda s: s

LANGUAGES = (
    ('es', _('español')),
    ('en', _('inglés')),
    ('fr', _('francés')),
    ('de', _('alemán')),
    ('it', _('italiano')),
    ('pt', _('portugués')),
    ('zh-hant', _('chino')),
    ('zh-hans', _('chino simplificado')),
    ('ja', _('japonés')),    
)

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

LOCALE_PATHS = (
 os.path.join(BASE_DIR, "locale"),
)

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/


#dar formato a fechas



# Configuration emails
# EMAIL_USE_TLS = True
# EMAIL_USE_SSL = False
# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_PORT = 587
# EMAIL_HOST_USER = 'patrick@medcombo.com'
# EMAIL_HOST_PASSWORD = 'Argiseru26'
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

# EMAIL_HOST = 'outlook.office365.com'
# EMAIL_PORT = 993#143
# EMAIL_HOST_USER = 'contacto@medcombo.com'
# EMAIL_HOST_PASSWORD = 'medcombo2019!'

#EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_USE_SSL = True
EMAIL_HOST = 'smtpout.secureserver.net'
EMAIL_HOST_USER = 'contacto@medcombo.es'
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
EMAIL_HOST_PASSWORD = '2019medcombo!'
EMAIL_PORT = 465

# Configuration Security Login
LOGIN_URL="/login/"

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',    
    'medcombo.configuration.usercustom.backends.EmailAuthBackend'
)

AUTH_USER_MODEL = 'usercustom.User'

#ASGI_APPLICATION = "medcombo.chat.routing.application"

CITIES_LIGHT_TRANSLATION_LANGUAGES = ['fr', 'en', 'de', 'pt', 'it', 'zh-hans', 'es']
"""CITIES_LIGHT_INCLUDE_COUNTRIES = ['FR']
CITIES_LIGHT_INCLUDE_CITY_TYPES = ['PPL', 'PPLA', 'PPLA2', 'PPLA3', 'PPLA4', 'PPLC', 'PPLF', 'PPLG', 'PPLL', 'PPLR', 'PPLS', 'STLMT',]"""

